---
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = TRUE)
```

<link rel="stylesheet" href="styles.css" type="text/css">

## Hey, I'm Sara


<font size = "3">I am data analyst with 7 years experience, ranging from analysis of geospatial data in government, product analytics at Indeed, and product and marketing analytics at the Content Strategy and Partnerships team at Comcast. My portfolio contains some of the work from my Master of Urban Spatial Analytics (MUSA) Program at the [University of Pennsylvania](https://www.design.upenn.edu/musa/about). I also have an MSc in Urban Planning in Developing and Transitional Regions from Oxford Brookes University.
<br><br>

Notable Projects:
From 2017 to 2020, I worked for the City of Philadelphia's Office of Information and Technology (OIT) in the CityGeo Team as a Lead GIS Analyst. In this role, I served as a project lead for the GIS component of the Next Generation 9-1-1 Project. This project will overhaul the existing dispatch system with tabular data in favor of a GIS-based dispatch system. One of the most critical deliverables of the project was creating an address point layer for Philadelphia that placed points at the front door of every building to optimize emergency response efficiency.
<br><br>


My full resume is available [here](files/Sara_Mattio_Resume.pdf).</font>
