<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Sara Mattio and Kate Sutton" />

<meta name="date" content="2019-12-20" />

<title>SmartAllocate – Predicting EMS Response for Smarter, More Efficient Ambulance Allocation</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/united.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css" data-origin="pandoc">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  { background-color: #f8f8f8; }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #c4a000; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #000000; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #000000; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #000000; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */

.sourceCode .row {
  width: 100%;
}
.sourceCode {
  overflow-x: auto;
}
.code-folding-btn {
  margin-right: -30px;
}
</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>


<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>

<link rel="stylesheet" href="styles.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Sara Mattio</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="Predicting_EMS_Response_VABeach.html">Predicting EMS Response</a>
</li>
<li>
  <a href="Predicting_Home_Prices_SF.html">Home Price Forecasting</a>
</li>
<li>
  <a href="Analyzing_Geospatial_Risk_Models.html">Geospatial Risk Modeling</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="contact.html">
    <span class="fa fa-envelope fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="http://github.com/ssmattio">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="https://www.linkedin.com/in/saramattio/">
    <span class="fa fa-linkedin fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">

<div class="btn-group pull-right">
<button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">SmartAllocate – Predicting EMS Response for Smarter, More Efficient Ambulance Allocation</h1>
<h4 class="author">Sara Mattio and Kate Sutton</h4>
<h4 class="date">12/20/2019</h4>

</div>


<p>Over the past 30 years, communication technologies have changed dramatically. As these technologies evolved, emergency response technology has lagged in modernization. The National Emergency Number Association (NENA) identified a need to completely overhaul the nation’s 911 systems in 2000; however, most municipalities have been slow to adapt this project. Unfortunately, out-of-date technology can result in slower emergency response – an inefficiency with potentially fatal outcomes.</p>
<p>Changes in business practices and adoption of new technology can be a challenging, lengthy process for small municipalities. While counties gradually improve emergency dispatch technology, it is possible to integrate intelligent, predictive algorithms into current business practices to optimize emergency response. This report analyzes the predictive modeling of SmartAllocate, an algorithm that increases efficiency in EMS response time by predicting the volume of EMS calls at any given time and day. By understanding where and when peak demand exists, ambulances are effectively allocated to the appropriate stations to handle predicted demand.</p>
<p>Incorporating intelligent predictive algorithms into emergency response has the potential to reduce fatal outcomes and reduce municipal spending. In this report, the process of building a predictive model for this use case will be analyzed with data provided by the City of Virginia Beach’s Open Data Portal.</p>
<p><strong>Click <a href="https://youtu.be/Ir93h7-oi2Q">here</a> for the video presentation of this project.</strong></p>
<div id="the-data" class="section level1">
<h1><span class="header-section-number">1</span> The Data</h1>
<p>The City of Virginia Beach has released an EMS Calls for Service dataset on their Open Data Portal which contains the date, time, location, and nature of the medical emergency for selected calls between 2010 and 2018. During the time this analysis took place, the City of Virginia Beach’s Open Data Portal underwent changes that resulted in the removal of the geocoded dataset used in this analysis. As a result, the only data made available to us was from June 14, 2010 to June 22, 2010. In total, the sample set contains 941 calls. Therefore, any tests and cross-validation conducted on the model could only utilize a small amount of data. Despite the limitations, this sample still serves as a useful cross-section of data as it takes place during Virginia Beach’s high season in the summer.</p>
<div id="reporting-bias-in-emergency-calls" class="section level2">
<h2><span class="header-section-number">1.1</span> Reporting Bias in Emergency Calls</h2>
<p>It should be noted that reporting bias likely exists in this dataset. With the exception of severe medical emergencies, it is likely that certain groups are more or less likely to call 911 for medical emergencies. Studies have found that those who have good health, good health insurance, no medical history, and no burden of medical costs are more likely to call 911 to report a medical emergency. Groups less likely to call 911 include those over the age of 65, of lower socioeconomic status, male, and in fair or poor health (Seo, M., Begley, C., Langabeer, J. R., &amp; DelliFraine, J. L., 2014). According to 2017 ACS 5-Year Estimates, nearly 13% of Virginia Beach is over the age of 65 and 18.4% of the population earns less than $25,000 per year. An estimated 8.9% of the population does not have health insurance coverage. While this model may have utility in predicting emergency medical <em>calls</em>, these results are likely to be inconsistent to where medical emergencies are actually taking place due to underreporting.</p>
</div>
</div>
<div id="exploring-the-data" class="section level1">
<h1><span class="header-section-number">2</span> Exploring The Data</h1>
<p>First, calls were mapped out to understand which areas are receiving the most calls. As expected, many calls are located along arterial roads in northern Virginia Beach, indicating that traffic accidents may serve as a useful predictive indicator.</p>
<div class="figure">
<img src="C:/Users/ssmat/Desktop/MUSA507/Final_Project/HeatMapBetter.png" alt="EMS Call Volume in Virginia Beach" />
<p class="caption">EMS Call Volume in Virginia Beach</p>
</div>
<p>This map shows the number of ambulances at each station, indicating that ambulances seem to be already well dispersed based on existing demand.</p>
<div class="figure">
<img src="C:/Users/ssmat/Desktop/MUSA507/Final_Project/EMSCallsMap.png" alt="Dispatch Stations in Virginia Beach, Symbolized by Ambulance Count" />
<p class="caption">Dispatch Stations in Virginia Beach, Symbolized by Ambulance Count</p>
</div>
<p>A relationship may also exist between the number of calls and certain demographic indicators, such as age, income, and race. The map below shoes the median age for census tracts using 2010 Census data from <code>tidycensus</code>. As previously suggested, tracts that have higher median ages seem to make less calls, while lower median age census tracts have a higher call density.</p>
<div class="figure">
<img src="Predicting_EMS_Response_VABeach_files/figure-html/unnamed-chunk-5-1.png" alt="..." width="672" />
<p class="caption">
…
</p>
</div>
<p>Mapping median household income results in a slightly different outcome than expected. Lower EMS call volume seems to occur in census tracts wtih a highest median income, but tracts with an average household income of $60,000 to $90,000 seem to be located in high-volume areas.</p>
<p><img src="Predicting_EMS_Response_VABeach_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>Race data shows a possible relationship between mainly white census tracts and medical emergency calls.</p>
<p><img src="Predicting_EMS_Response_VABeach_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>Finally, given the relationship between weather and traffic accidents, weather conditions may also be a useful predictor for EMS call volume. Using the <code>riem</code> package, a weather panel can be created for the date range of the sample.</p>
<pre><code>##    interval60                   Temperature    Precipitation    
##  Min.   :2010-06-14 00:00:00   Min.   :66.02   Min.   :0.00000  
##  1st Qu.:2010-06-16 00:30:00   1st Qu.:73.94   1st Qu.:0.00000  
##  Median :2010-06-18 00:00:00   Median :78.08   Median :0.00000  
##  Mean   :2010-06-17 23:53:24   Mean   :78.63   Mean   :0.03414  
##  3rd Qu.:2010-06-19 23:30:00   3rd Qu.:82.94   3rd Qu.:0.00000  
##  Max.   :2010-06-21 23:00:00   Max.   :89.96   Max.   :3.83000  
##    Wind_Speed    
##  Min.   : 0.000  
##  1st Qu.: 5.000  
##  Median : 6.000  
##  Mean   : 6.351  
##  3rd Qu.: 8.000  
##  Max.   :23.000</code></pre>
<p>The data is then categorized by precipitation, wind speed, and temperature for the time period of this analysis. Weather patterns during this time, particularly high heat and precipitation may cause more health emergencies and traffic accidents, resulting in increased medical emergency calls.</p>
<p><img src="Predicting_EMS_Response_VABeach_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
</div>
<div id="the-model" class="section level1">
<h1><span class="header-section-number">3</span> The Model</h1>
<p>It should be noted that because a limited sample set of data was provided to us by the City of Virginia Beach’s Open Data Portal, we were unable to train and test the model on a large sample size nor on a wider time period.</p>
<div id="space-time-process" class="section level2">
<h2><span class="header-section-number">3.1</span> Space-Time Process</h2>
<p>Because the data has both spatial and temporal features, the space-time process creates time-based features that are combined with spatial features to create a panel with every possible observation for space-time combinations. The <code>EMS_calls</code> dataset contains several temporal features, including dispatch time and entry date, but for this analysis, the <code>call_date_and_time</code> field was chosen. A 60-minute time interval was added to eventually create time lags. The resulting <code>Call_Time</code> panel is shown below.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb2-1" title="1">study.panel &lt;-<span class="st"> </span></a>
<a class="sourceLine" id="cb2-2" title="2"><span class="st">  </span><span class="kw">expand.grid</span>(<span class="dt">interval60 =</span> <span class="kw">unique</span>(calls<span class="op">$</span>interval60),</a>
<a class="sourceLine" id="cb2-3" title="3">              <span class="dt">TRACTCE10 =</span> <span class="kw">unique</span>(calls<span class="op">$</span>TRACTCE10))</a>
<a class="sourceLine" id="cb2-4" title="4"></a>
<a class="sourceLine" id="cb2-5" title="5">call.panel &lt;-<span class="st"> </span></a>
<a class="sourceLine" id="cb2-6" title="6"><span class="st">  </span>calls <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb2-7" title="7"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">Call_Counter =</span> <span class="dv">1</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb2-8" title="8"><span class="st">  </span><span class="kw">right_join</span>(study.panel) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb2-9" title="9"><span class="st">  </span><span class="kw">group_by</span>(interval60, TRACTCE10) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb2-10" title="10"><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">Call_Count =</span> <span class="kw">sum</span>(Call_Counter, <span class="dt">na.rm=</span>T))</a>
<a class="sourceLine" id="cb2-11" title="11"></a>
<a class="sourceLine" id="cb2-12" title="12">call.panel<span class="op">$</span>interval60<span class="fl">.3</span> &lt;-<span class="st"> </span><span class="kw">parse_date_time</span>(call.panel<span class="op">$</span>interval60, <span class="dt">orders =</span> <span class="st">&quot;mdy hm&quot;</span>)</a>
<a class="sourceLine" id="cb2-13" title="13"></a>
<a class="sourceLine" id="cb2-14" title="14">call.panel<span class="op">$</span>week &lt;-<span class="st"> </span><span class="kw">week</span>(call.panel<span class="op">$</span>interval60<span class="fl">.3</span>)</a>
<a class="sourceLine" id="cb2-15" title="15">call.panel<span class="op">$</span>dotw &lt;-<span class="st"> </span><span class="kw">wday</span>(call.panel<span class="op">$</span>interval60<span class="fl">.3</span>)</a></code></pre></div>
<p>To incorporate the weather data to the panel, the time field is cleaned up with the <code>is.POSIXct</code> function and joined to the <code>call.panel</code>,</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" title="1"><span class="kw">is.POSIXct</span>(weather.Panel<span class="op">$</span>interval60<span class="fl">.3</span>)</a></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" title="1"><span class="kw">is.POSIXct</span>(call.panel<span class="op">$</span>interval60<span class="fl">.3</span>)</a></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" title="1">weather.Panel<span class="op">$</span>interval60<span class="fl">.3</span> &lt;-<span class="st"> </span><span class="kw">parse_date_time</span>(weather.Panel<span class="op">$</span>interval60, <span class="dt">orders =</span> <span class="st">&quot;ymd hms&quot;</span>)</a>
<a class="sourceLine" id="cb7-2" title="2"></a>
<a class="sourceLine" id="cb7-3" title="3">call.panel &lt;-<span class="st"> </span><span class="kw">left_join</span>(call.panel, weather.Panel, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;interval60.3&quot;</span>, <span class="st">&quot;interval60.3&quot;</span>))</a></code></pre></div>
<p>Next, to predict time series trends, time lags are incorporated into the model. Time lags provide additional insight into call volume during a given time period through the comparison of the hours before and after high-volume time periods. Because this sample set contains a holiday that may affect EMS call volume (Father’s Day), holiday features were incorporated into the model as fixed effects.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb8-1" title="1">call.panel &lt;-<span class="st"> </span></a>
<a class="sourceLine" id="cb8-2" title="2"><span class="st">  </span>call.panel <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb8-3" title="3"><span class="st">  </span><span class="kw">arrange</span>(TRACTCE10, interval60<span class="fl">.3</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb8-4" title="4"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">lagHour =</span> dplyr<span class="op">::</span><span class="kw">lag</span>(Call_Count,<span class="dv">1</span>),</a>
<a class="sourceLine" id="cb8-5" title="5">         <span class="dt">lag2Hours =</span> dplyr<span class="op">::</span><span class="kw">lag</span>(Call_Count,<span class="dv">2</span>),</a>
<a class="sourceLine" id="cb8-6" title="6">         <span class="dt">lag3Hours =</span> dplyr<span class="op">::</span><span class="kw">lag</span>(Call_Count,<span class="dv">3</span>),</a>
<a class="sourceLine" id="cb8-7" title="7">         <span class="dt">lag4Hours =</span> dplyr<span class="op">::</span><span class="kw">lag</span>(Call_Count,<span class="dv">4</span>),</a>
<a class="sourceLine" id="cb8-8" title="8">         <span class="dt">lag12Hours =</span> dplyr<span class="op">::</span><span class="kw">lag</span>(Call_Count,<span class="dv">12</span>),</a>
<a class="sourceLine" id="cb8-9" title="9">         <span class="dt">lag1day =</span> dplyr<span class="op">::</span><span class="kw">lag</span>(Call_Count,<span class="dv">24</span>),</a>
<a class="sourceLine" id="cb8-10" title="10">         <span class="dt">holiday =</span> <span class="kw">as.factor</span>(<span class="kw">ifelse</span>(<span class="kw">yday</span>(interval60<span class="fl">.3</span>) <span class="op">==</span><span class="st"> </span><span class="dv">171</span>,<span class="dv">1</span>,<span class="dv">0</span>))) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb8-11" title="11"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">day =</span> <span class="kw">yday</span>(interval60<span class="fl">.3</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb8-12" title="12"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">holidayLag =</span> <span class="kw">case_when</span>(</a>
<a class="sourceLine" id="cb8-13" title="13">                                dplyr<span class="op">::</span><span class="kw">lead</span>(holiday, <span class="dv">1</span>) <span class="op">==</span><span class="st"> </span><span class="dv">1</span> <span class="op">~</span><span class="st"> &quot;MinusOneDay&quot;</span>),</a>
<a class="sourceLine" id="cb8-14" title="14">         <span class="dt">holidayLag =</span> <span class="kw">replace_na</span>(holidayLag, <span class="dv">0</span>))</a>
<a class="sourceLine" id="cb8-15" title="15"></a>
<a class="sourceLine" id="cb8-16" title="16">dplyr<span class="op">::</span><span class="kw">select</span>(<span class="kw">st_set_geometry</span>(call.panel, <span class="ot">NULL</span>), </a>
<a class="sourceLine" id="cb8-17" title="17">              interval60<span class="fl">.3</span>, TRACTCE10, Call_Count, </a>
<a class="sourceLine" id="cb8-18" title="18">              lagHour, lag2Hours)</a></code></pre></div>
<pre><code>## # A tibble: 17,664 x 6
## # Groups:   interval60.x [184]
##    interval60.x    interval60.3        TRACTCE10 Call_Count lagHour lag2Hours
##  * &lt;chr&gt;           &lt;dttm&gt;              &lt;fct&gt;          &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;
##  1 6/14/2010 0:00  2010-06-14 00:00:00 040000             0      NA        NA
##  2 6/14/2010 1:00  2010-06-14 01:00:00 040000             0      NA        NA
##  3 6/14/2010 2:00  2010-06-14 02:00:00 040000             0      NA        NA
##  4 6/14/2010 3:00  2010-06-14 03:00:00 040000             0      NA        NA
##  5 6/14/2010 4:00  2010-06-14 04:00:00 040000             0      NA        NA
##  6 6/14/2010 6:00  2010-06-14 06:00:00 040000             0      NA        NA
##  7 6/14/2010 7:00  2010-06-14 07:00:00 040000             0      NA        NA
##  8 6/14/2010 8:00  2010-06-14 08:00:00 040000             1      NA        NA
##  9 6/14/2010 9:00  2010-06-14 09:00:00 040000             0      NA        NA
## 10 6/14/2010 10:00 2010-06-14 10:00:00 040000             0      NA        NA
## # ... with 17,654 more rows</code></pre>
<p>By breaking down the number of calls by day, several patterns occur. During the weekday, fewer calls take place in the early morning, while volume seems to increase mid-day. On the weekends, volume appears to be lower and steadier. For the last day of the set, only a limited amount of calls were provided in the dataset, resulting in a perceived abnormal volume.</p>
<p><img src="Predicting_EMS_Response_VABeach_files/figure-html/unnamed-chunk-13-1.png" width="1536" /></p>
<p>The plots below explore the relationship between EMS call counts and time lag functions. Based on the close correlation of these features in all time lag functions, these functions should serve as a strong predictor.</p>
<p><img src="Predicting_EMS_Response_VABeach_files/figure-html/unnamed-chunk-14-1.png" width="1152" /></p>
</div>
<div id="the-final-model" class="section level2">
<h2><span class="header-section-number">3.2</span> The Final Model</h2>
<p>To train and test the model, <code>call.Train</code> and <code>call.Test</code> datasets were formed. Four regression models were developed using an increasing amount of indicators. The final two include time lag features.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb10-1" title="1">call.panel<span class="op">$</span>tract2 &lt;-<span class="st"> </span><span class="kw">as.character</span>(call.panel<span class="op">$</span>TRACTCE10)</a>
<a class="sourceLine" id="cb10-2" title="2">call.Train &lt;-<span class="st"> </span><span class="kw">subset</span>(call.panel, week <span class="op">==</span><span class="st"> </span><span class="dv">24</span> <span class="op">&amp;</span><span class="st"> </span>dotw <span class="op">&lt;</span><span class="st"> </span><span class="dv">7</span>)</a>
<a class="sourceLine" id="cb10-3" title="3">call.Test &lt;-<span class="st"> </span><span class="kw">filter</span>(call.panel, day <span class="op">&gt;</span><span class="st"> </span><span class="dv">169</span>)</a>
<a class="sourceLine" id="cb10-4" title="4"></a>
<a class="sourceLine" id="cb10-5" title="5">reg1 &lt;-<span class="st"> </span></a>
<a class="sourceLine" id="cb10-6" title="6"><span class="st">  </span><span class="kw">lm</span>(Call_Count <span class="op">~</span><span class="st">  </span><span class="kw">hour</span>(interval60<span class="fl">.3</span>) <span class="op">+</span><span class="st"> </span>dotw ,  <span class="dt">data=</span>call.Train)</a>
<a class="sourceLine" id="cb10-7" title="7"></a>
<a class="sourceLine" id="cb10-8" title="8">reg2 &lt;-</a>
<a class="sourceLine" id="cb10-9" title="9"><span class="st">  </span><span class="kw">lm</span>(Call_Count <span class="op">~</span><span class="st"> </span><span class="kw">hour</span>(interval60<span class="fl">.3</span>) <span class="op">+</span><span class="st"> </span>dotw <span class="op">+</span><span class="st"> </span>tract2, <span class="dt">data =</span> call.Train)</a>
<a class="sourceLine" id="cb10-10" title="10"></a>
<a class="sourceLine" id="cb10-11" title="11">reg3 &lt;-</a>
<a class="sourceLine" id="cb10-12" title="12"><span class="st">  </span><span class="kw">lm</span>(Call_Count <span class="op">~</span><span class="st"> </span><span class="kw">hour</span>(interval60<span class="fl">.3</span>) <span class="op">+</span><span class="st"> </span>dotw <span class="op">+</span><span class="st"> </span>tract2 <span class="op">+</span><span class="st"> </span>lagHour <span class="op">+</span>lag2Hours <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb10-13" title="13"><span class="st">       </span>lag3Hours <span class="op">+</span><span class="st"> </span>lag4Hours <span class="op">+</span><span class="st"> </span>lag12Hours, <span class="dt">data =</span> call.Train)</a>
<a class="sourceLine" id="cb10-14" title="14"></a>
<a class="sourceLine" id="cb10-15" title="15">reg4 &lt;-<span class="st"> </span><span class="kw">lm</span>(Call_Count <span class="op">~</span><span class="st"> </span><span class="kw">hour</span>(interval60<span class="fl">.3</span>) <span class="op">+</span><span class="st"> </span>dotw <span class="op">+</span><span class="st"> </span>tract2 <span class="op">+</span><span class="st"> </span>lagHour <span class="op">+</span>lag2Hours <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb10-16" title="16"><span class="st">             </span>lag3Hours <span class="op">+</span><span class="st"> </span>lag4Hours <span class="op">+</span><span class="st"> </span>lag12Hours <span class="op">+</span><span class="st"> </span>Temperature <span class="op">+</span><span class="st"> </span>Precipitation <span class="op">+</span><span class="st"> </span>Wind_Speed, <span class="dt">data =</span> call.Train)</a></code></pre></div>
</div>
<div id="testing-and-validating-the-model" class="section level2">
<h2><span class="header-section-number">3.3</span> Testing and Validating the Model</h2>
<p>To test the model, a nested data frame of the test data by week. A functin is created (<code>model_pred</code>) that can be mapped onto each data frame of the nested structure.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" title="1">call.Test.weekNest &lt;-<span class="st"> </span></a>
<a class="sourceLine" id="cb11-2" title="2"><span class="st">  </span>call.Test <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb11-3" title="3"><span class="st">  </span><span class="kw">filter</span>(<span class="op">!</span><span class="kw">is.na</span>(lagHour))<span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb11-4" title="4"><span class="st">  </span><span class="kw">filter</span>(<span class="op">!</span><span class="kw">is.na</span>(lag2Hours))<span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb11-5" title="5"><span class="st">  </span><span class="kw">filter</span>(<span class="op">!</span><span class="kw">is.na</span>(lag3Hours))<span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb11-6" title="6"><span class="st">  </span><span class="kw">filter</span>(<span class="op">!</span><span class="kw">is.na</span>(lag4Hours))<span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb11-7" title="7"><span class="st">  </span><span class="kw">filter</span>(<span class="op">!</span><span class="kw">is.na</span>(lag12Hours))<span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb11-8" title="8"><span class="st">  </span><span class="kw">nest</span>(<span class="op">-</span>week)</a>
<a class="sourceLine" id="cb11-9" title="9"></a>
<a class="sourceLine" id="cb11-10" title="10">model_pred &lt;-<span class="st"> </span><span class="cf">function</span>(dat, fit){</a>
<a class="sourceLine" id="cb11-11" title="11">  pred &lt;-<span class="st"> </span><span class="kw">predict</span>(fit, <span class="dt">newdata =</span> dat)</a>
<a class="sourceLine" id="cb11-12" title="12">  }</a></code></pre></div>
<p>The predictions can then be run and summarized as follows. The results show that 0.0531 calls take place per hour per census tract in Virginia Beach. This number seems lower than expected, which can be explained by the limited number of records in the dataset.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb12-1" title="1">week_predictions &lt;-<span class="st"> </span></a>
<a class="sourceLine" id="cb12-2" title="2"><span class="st">  </span>call.Test.weekNest <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb12-3" title="3"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">ATime =</span> <span class="kw">map</span>(<span class="dt">.x =</span> data, <span class="dt">fit =</span> reg1, <span class="dt">.f =</span> model_pred),</a>
<a class="sourceLine" id="cb12-4" title="4">         <span class="dt">BTime_Space =</span> <span class="kw">map</span>(<span class="dt">.x =</span> data, <span class="dt">fit =</span> reg2, <span class="dt">.f =</span> model_pred),</a>
<a class="sourceLine" id="cb12-5" title="5">         <span class="dt">CTime_Space_TimeLag =</span> <span class="kw">map</span>(<span class="dt">.x =</span> data, <span class="dt">fit =</span> reg3, <span class="dt">.f =</span> model_pred),</a>
<a class="sourceLine" id="cb12-6" title="6">         <span class="dt">DTime_Space_TimeLag_Weather =</span> <span class="kw">map</span>(<span class="dt">.x =</span> data, <span class="dt">fit =</span> reg4, <span class="dt">.f =</span> model_pred))</a>
<a class="sourceLine" id="cb12-7" title="7"></a>
<a class="sourceLine" id="cb12-8" title="8">week_predictions &lt;-</a>
<a class="sourceLine" id="cb12-9" title="9"><span class="st">  </span>week_predictions <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb12-10" title="10"><span class="st">  </span><span class="kw">gather</span>(Regression, Prediction, <span class="op">-</span>data, <span class="op">-</span>week) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb12-11" title="11"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">Observed =</span> <span class="kw">map</span>(data, pull, Call_Count),</a>
<a class="sourceLine" id="cb12-12" title="12">         <span class="dt">Absolute_Error =</span> <span class="kw">map2</span>(Observed, Prediction,  <span class="op">~</span><span class="st"> </span><span class="kw">abs</span>(.x <span class="op">-</span><span class="st"> </span>.y)),</a>
<a class="sourceLine" id="cb12-13" title="13">         <span class="dt">MAE =</span> <span class="kw">map_dbl</span>(Absolute_Error, mean, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>),</a>
<a class="sourceLine" id="cb12-14" title="14">         <span class="dt">sd_AE =</span> <span class="kw">map_dbl</span>(Absolute_Error, sd, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>))</a>
<a class="sourceLine" id="cb12-15" title="15"></a>
<a class="sourceLine" id="cb12-16" title="16">week_predictions</a></code></pre></div>
<pre><code>## # A tibble: 4 x 8
##    week data      Regression     Prediction Observed Absolute_Error    MAE sd_AE
##   &lt;dbl&gt; &lt;list&gt;    &lt;chr&gt;          &lt;list&gt;     &lt;list&gt;   &lt;list&gt;          &lt;dbl&gt; &lt;dbl&gt;
## 1    25 &lt;tibble ~ ATime          &lt;dbl [6,0~ &lt;dbl [6~ &lt;dbl [6,048]&gt;  0.0990 0.217
## 2    25 &lt;tibble ~ BTime_Space    &lt;dbl [6,0~ &lt;dbl [6~ &lt;dbl [6,048]&gt;  0.0966 0.214
## 3    25 &lt;tibble ~ CTime_Space_T~ &lt;dbl [6,0~ &lt;dbl [6~ &lt;dbl [6,048]&gt;  0.0967 0.214
## 4    25 &lt;tibble ~ DTime_Space_T~ &lt;dbl [6,0~ &lt;dbl [6~ &lt;dbl [6,048]&gt;  0.0984 0.214</code></pre>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb14-1" title="1">call.Test.weekNest <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb14-2" title="2"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">Call_Count =</span> <span class="kw">map</span>(data, pull, Call_Count),</a>
<a class="sourceLine" id="cb14-3" title="3">         <span class="dt">Mean_Call_Count =</span> <span class="kw">map_dbl</span>(Call_Count, mean))</a></code></pre></div>
<pre><code>## # A tibble: 1 x 4
##    week data                  Call_Count    Mean_Call_Count
##   &lt;dbl&gt; &lt;list&gt;                &lt;list&gt;                  &lt;dbl&gt;
## 1    25 &lt;tibble [6,048 x 20]&gt; &lt;dbl [6,048]&gt;          0.0531</code></pre>
<p>To analyze the model further, the Mean Absolute Errors (MAE) for each model can be shown by week. It appears that the differences among the four models are minimal, although incorporating weather features improved the model slightly. Time lag features appears to have worsened the model slightly; however the difference is minimal.</p>
<p><img src="Predicting_EMS_Response_VABeach_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p>Finally, the mean and predicteed observed volume of calls can be observed to compare goodness of fit. While Model D appears to be somewhat closely aligned, the other models do not match the predicted observations as closely as expected. The correlation plots for calls and time lag do not seems to be as strong of a predictor as originally suggested.</p>
<p><img src="Predicting_EMS_Response_VABeach_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p>This analysis intended to include validation tests by space; however, the model produced too many <code>NA</code> values and results could not be mapped.</p>
</div>
</div>
<div id="conclusion" class="section level1">
<h1><span class="header-section-number">4</span> Conclusion</h1>
<p>The idea behind this analysis was to explore data related to EMS call volume and utilize these features in a model which would ultimately be tested to determine accuracy and generalizability. While Model D was somewhat accurate in its predictions with an average MAE of 0.0984, compared to the average MAE of the tracts of 0.0531, the model’s MAE is not as strong. It is very surprising that models with time lag features did not show an improvement over those without time lag features, especially considering the correlation values for time lag features were above 0.90. Identifying the source of this problem would create the most substantial improvement in this model. As far as the generalizability of the model, the model is not accurate enough to assess its generalizability. Despite the initial shortcomings of the model at this stage, there is strong potential for improvement in further stages of development. First, a significantly larger sample size should be used. Without the API from the City’s Open Data Portal, it was challenging to properly assess a wide selection of data. Although geocoded data was provided to us by another group, the datetime formatting created a lot of issues and we chose to use the data we already had saved in our environment instead. Having at least 10,000 records would have allowed for a more thorough analysis. The time period used was also problematic. Unfortunately, the only data available to us was from a 9-day time period in June 2010. Creating a time-space model with 9 days worth of data was challenging and ultimately not useful in creating a generalizable model. In future stages of development of this model, using a larger, more recent dataset could create a more robust model.</p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("show" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
